server:
  port: 8300
###服务名称(服务注册到eureka名称)
spring:
  application:
    #    该服务别名
    name: app-personal-order
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
    #    注册到服务中心，让注册中心检测自己
    register-with-eureka: true
    #    进行检索
    fetch-registry: true
