server:
  port: 8200
spring:
  application:
    #    该服务别名
    name: app-personal-member
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka
    #    注册到服务中心
    register-with-eureka: true
    #    进行检索
    fetch-registry: true
