server:
  port: 8100
###eureka 基本信息配置
eureka:
  instance:
    ###注册到eurekaip地址 eureka服务端的实力名称
    hostname: 127.0.0.1
  client:
    serviceUrl:
#      设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址(单机版)
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/   # 集群版
    ###因为自己是服务注册中心，不需要自己注册自己。
    register-with-eureka: false
    ###因为自己是服务注册中心：我的职责就是维护服务实例 不需要检索服务
    fetch-registry: false

#    服务注册中心也有单节点多节点，即一个/多个服务注册中心
